version: '3.1'

services:
  db:
    image: "postgis/postgis:16-3.4-alpine"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: inegi
    ports:
      - 5432:5432
    volumes:
      - ./migrations/sql/:/docker-entrypoint-initdb.d/